// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SebastianSuarez_AP1_P1.DAL;

#nullable disable

namespace SebastianSuarez_AP1_P1.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20241013031321_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("SebastianSuarez_AP1_P1.Models.Cobros", b =>
                {
                    b.Property<int>("CobroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("Monto")
                        .HasColumnType("INTEGER");

                    b.HasKey("CobroId");

                    b.ToTable("Cobros");
                });

            modelBuilder.Entity("SebastianSuarez_AP1_P1.Models.CobrosDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CobroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CobrosId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PrestamoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ValorCobrado")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("CobrosId");

                    b.ToTable("CobrosDetalle");
                });

            modelBuilder.Entity("SebastianSuarez_AP1_P1.Models.Prestamos", b =>
                {
                    b.Property<int>("PrestamoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Balance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Concepto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Deudor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Monto")
                        .HasColumnType("INTEGER");

                    b.HasKey("PrestamoId");

                    b.ToTable("Prestamo");

                    b.HasData(
                        new
                        {
                            PrestamoId = 1,
                            Deudor = "Pedro"
                        },
                        new
                        {
                            PrestamoId = 2,
                            Deudor = "Angel"
                        },
                        new
                        {
                            PrestamoId = 3,
                            Deudor = "Diego"
                        });
                });

            modelBuilder.Entity("SebastianSuarez_AP1_P1.Models.CobrosDetalle", b =>
                {
                    b.HasOne("SebastianSuarez_AP1_P1.Models.Cobros", null)
                        .WithMany("CobrosDetalles")
                        .HasForeignKey("CobrosId");
                });

            modelBuilder.Entity("SebastianSuarez_AP1_P1.Models.Cobros", b =>
                {
                    b.Navigation("CobrosDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
